name: Test Dotfiles Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-setup:
    runs-on: macos-latest
    
    steps:
    - name: Checkout dotfiles
      uses: actions/checkout@v4
      with:
        path: dotfiles
    
    - name: Move dotfiles to home directory
      run: mv dotfiles ~/dotfiles
    
    - name: Set up Git config for testing
      run: |
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
    
    - name: Run dry-run setup check
      run: ~/dotfiles/scripts/setup.sh --dry-run
    
    - name: Run install scripts setup
      run: ~/dotfiles/scripts/setup.sh
      env:
        # Skip interactive prompts
        CI: true
    
    - name: Verify installations
      run: ~/dotfiles/scripts/setup.sh --verify